### ISSUE TITLE
Possible Release?

### ISSUE THREAD

**Issue by joelturnbull** [lostisland/faraday_middleware#115]
I could really use the current master version of the follow redirects middleware ( with the code that escapes the characters in redirect urls ). Is there any possibility you could do a small release? Thanks!

**Comment by pengwynn** [comment]
@mislav Looking at the diff since v0.9.1 I'm guessing this would be v0.10.0 for the new redirect stuff? I didn't see anything obviously breaking.

**Comment by mislav** [comment]
Released both 0.9.2 (no new features) and 0.10.0 (features).

**Comment by joelturnbull** [comment]
Thank you :+1:
