### ISSUE TITLE
Problem with caching on 0.10.0

### ISSUE THREAD

**Issue by espen** [lostisland/faraday_middleware#116]
I don't see any significant changes 0.9.2 vs 0.10.0 but using Faraday Middleware Caching with Her and Dalli results in this error on 0.10.0: `undefined method 'read' for #<Dalli::Client:0x007f9ba40faef0>`. No problems with 0.9.2 (no other changes).

**Comment by mislav** [comment]
Thanks for reporting.

[We switched from `cache.fetch` method](https://github.com/lostisland/faraday_middleware/compare/v0.9.2...v0.10.0#diff-32d8ad0f070291407b5ceb8e788fb40f) to `cache.read` + `cache.write`. Can you check why Dalli::Client doesn't support the `read` method?

**Comment by mislav** [comment]
Hmm it seems that Dalli supports `get` + `set` instead. Our caching middleware is designed to accept a ActiveSupport::Cache::Store-like object that responds to `fetch`, `read` and `write`. Maybe you should wrap your Dalli::Client instance as a ActiveSupport::Cache::Store.

**Comment by espen** [comment]
Yup. Thanks.

**Comment by vbalazs** [comment]
There is an ActiveSupport::Cache DalliStore implementation in the gem: see `lib/active_support/cache/dalli_store.rb`

**Comment by espen** [comment]
I ended up doing `ActiveSupport::Cache.lookup_store( Myapp::Application.config.cache_store )`
