### ISSUE TITLE
FollowRedirects on infinite loop because of Safe_Escape 

### ISSUE THREAD

**Issue by hugocore** [lostisland/faraday_middleware#117]
Hi guys,

One or our customers is using Angular.js on their website and we are using Faraday to crawl it. The problem is that we are getting an infinitive loop when we try to resolve/follow their URLs, resulting in `FaradayMiddleware::RedirectLimitReached: too many redirects; last one to: ..`

Here are the steps:

- GET `http://www.gleamworld.com/looks/311723`
- Web Server checks for `#!` because it's not there returns a 301 (Redirect) with `http://www.gleamworld.com/#!/looks/311723`
- Faraday follows the redirect but escapes the URL with `http://www.gleamworld.com/%23!/looks/311723`
- Web Server checks for `#!` because it's not there returns a 301 (Redirect) with `http://www.gleamworld.com/#!/%23!/looks/311723`
- Faraday follows the redirect but escapes the URL with `http://www.gleamworld.com/%23!/%23!/looks/311723`
- ....

Angular uses # for navigation purposes. The `!` it's because they are using this specification from Google https://developers.google.com/webmasters/ajax-crawling/docs/specification.

The problem is in this function https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/response/follow_redirects.rb#L120

I will like to have your feedback to understand if this is a problem on the library or on the website. My believe is that Faraday should not escape the # because it's not in the URI_UNSAFE reg exp. *Also, their links work with the browser.*

**Comment by mislav** [comment]
Thanks for reporting! We should definitely ignore anything after `#!` in these URLs because the hash fragment is only useful to web browsers and should be ignored by HTTP clients such as Faraday.
