### ISSUE TITLE
PUT & DELETE request strips double slash.

### ISSUE THREAD

**Issue by radhakmk** [lostisland/faraday_middleware#125]
Hi Team,

Issue while sending PUT & DELETE request to an OAUTH Server. I am trying to update an Scope entity with the guid `http://website.com/auth/listings`

GEM versions:
    faraday (0.8.5)
    faraday_middleware (0.9.0)

Below is the request from my code:

```
put https://login.website.net/oauth/api/Scopes('http://website.com/auth/listings')
delete https://login.website.net/oauth/api/Scopes('http://website.com/auth/listings')
```

Faraday gem converts the double slash to single slash as below while sending request to OAUTH Server.

```
put https://login.website.net/oauth/api/Scopes('http:/website.com/auth/listings')
delete https://login.website.net/oauth/api/Scopes('http:/website.com/auth/listings')
```

Because it converts double slash to single slash, OAUTH server responds back with "entity not found exception" 

Can anyone suggest a fix for this? 

Thanks,
Mohan

**Comment by mislav** [comment]
Hi, I can't find proof that Faraday does strip the double slash internally. Could you share some minimal example code that demonstrates this? Is it possible that this is caused by some middleware?

**Comment by radhakmk** [comment]
_require 'faraday_middleware'

 @perf_connection = Faraday.new(url: $config.oauth.perf.host, :ssl => {:verify => ssl}) do |faraday|
      faraday.headers['Authorization'] = "Bearer #{@oauth_perf_token}"
      faraday.headers['Accept'] = 'application/json'
      faraday.request :json
      faraday.response :xml, :content_type => /\bxml$/
      faraday.response :json, :content_type => /\bjson$/
      faraday.use :instrumentation
      faraday.response :logger
      faraday.adapter Faraday.default_adapter
    end_

_response = @perf_connection.put "#{$config.oauth.path}/Scopes('https://login.qa.net/pdp/tve')", data.to_json_

Above statement is my request and if you not the guid (**'https://login.qa.net/pdp/tve'**). Take a look at the response, you can notice one slash has been stripped from the request. 

**output of faraday response:
-----------------------------------------------------------------------------------------------------------------------------------**
### _#<Faraday::Response:0x007fbb189ec8b8 @env={:method=>:put, :body=>{"error"=>{"code"=>"NotFoundException", "message"=>{"lang"=>"en-US", "value"=>"Entity with key = https:/login.qa.net/pdp/tve"}}}, :url=>#<URI::HTTPS:0x007fbb18ac2c60 URL:https://login-perf.test.net/oauth/api/Scopes('https:/login.qa.net/pdp/tve')>, :request_headers=>{"Authorization"=>"Bearer ***********", "Accept"=>"application/json", "Content-Type"=>"application/json"}, :parallel_manager=>nil, :request=>{:proxy=>nil}, :ssl=>{:verify=>false}, :status=>404, :response_headers=>{"date"=>"Tue, 21 Jun 2016 17:54:54 GMT", "server"=>"Apache", "dataserviceversion"=>"1.0", "x-powered-by"=>"Servlet/2.5 JSP/2.1", "vary"=>"Accept-Encoding", "connection"=>"close", "transfer-encoding"=>"chunked", "content-type"=>"application/json;charset=utf-8"}, :response=>#<Faraday::Response:0x007fbb189ec8b8 ...>}, @on_complete_callbacks=[]>_

**Comment by mislav** [comment]
Thanks for the details. I see the single slash, but I doubt that Faraday is responsible for this.

1. Did you change `Faraday.default_adapter` or did it remain net/http?
2. Can you disable `response :json` middleware and inspect the raw HTTP response instead? Check if the double slash is present there.

**Comment by radhakmk** [comment]
Hi Mislav, Something is happening on this method "build_exclusive_url" in /lib/faraday/connection.rb
How to overide this method in my application?

**Comment by iMacTia** [comment]
@radhakmk Since this issue seems related to `faraday` and not `faraday_middleware`, please re-raise this issue[there](
https://github.com/lostisland/faraday) if it's still a problem for you.
