### ISSUE TITLE
Add a way to compose Hashie behavior

### ISSUE THREAD

**Issue by dblock** [lostisland/faraday_middleware#129]
Something like `FaradayMiddleware::HashieExtensions` that would allow us to compose things like `Hashie::Extensions::MethodAccess` and similar on-demand, and not default to using `Hashie::Mash` or `Hashie::Rash`.

**Comment by elyobo** [comment]
This is already pretty easily doable with the mashify middleware.

* Create your own Hash class using whatever hashie extensions you need.
* Use the mashify middleware, passing in your new class as the mash_class option.

**Comment by elyobo** [comment]
(That's all that the Rashify middleware does anyway - it just uses tcocca's Hashie::Rash as the mash_class).

**Comment by iMacTia** [comment]
After reading #91 I think we can close this one as there's no change required code-wise.
Thanks @elyobo for explaining how to solve this.
