### ISSUE TITLE
access_token is showable when using OAuth2 middleware

### ISSUE THREAD

**Issue by syguer** [lostisland/faraday_middleware#130]
Hi.
I've noticed that access_token is showable when using OAuth2 middleware like...

```ruby
require 'faraday'
require 'faraday_middleware'

conn = Faraday.new(url: "https://example.com") do |builder|
  builder.request :oauth2, 'access_token'
end

conn.get
#=> access to https://example.com/?access_token=access_token
```

The code is here.
https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/request/oauth2.rb#L37

This behavior looks like not secure for me. (Of course I know this is one of the popular usage.)
So I think adding access_token to url parameter should be optional.
How do you think this?

Sorry for my poor English :sake: 
Regards.

**Comment by cjford** [comment]
+1

Even over SSL, it is preferable to use the authorization header over the URL parameter from a security standpoint because it may show up in things like server logs or browser caches.

I'm happy to try my hand at submitting a PR for this when I get a chance, but any implementation input is welcome. Perhaps allow :param_name to be blank/nil, and in that case exclude the parameter entirely instead of raising an ArgumentError?

**Comment by iMacTia** [comment]
Hi guys,

@syguer, thanks for pointing this out!
Surely this behaviour is against the Oauth2 standard and should thus be fixed.
According to the [spec](https://tools.ietf.org/html/rfc6749#section-7), the token should be sent over the `Authorization` header, prefixed by the "Bearer" keyword. A greater level of security can also be implemented with the MAC keyword and hashing of the token.

Unfortunately, we don't know how many people out there are using this middleware so we should try to make this as much backward compatible as possible. I suggest the following "course of action"

* Add a middleware option to choose the way the token will be sent (option name can be for e.g. "via" or "token_style" or similar). This will default to `:param` for the time being, which is the current (wrong) way. 
* You can now implement additional ways of sending the token (Bearer for sure, mac if you have time) and use the correct one based on the new option.
* Add a warning message in case the default value is used (actually, no value is given to the option) explaining that in the next major update "Bearer" will be the default one.
* Update the documentation to explain the new option and te warning message.

In the next big release, we can then make "Bearer" the default 😁
I hope this is clear, but if not please do let me know!
thanks in advance if you want to spend some time on it!

**Comment by iMacTia** [comment]
@syguer @cjford any reason you're not using the [Oauth middleware](https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/request/oauth.rb)?

It's similar to Oauth2 middleware, but following the RFC documentation.
I think you could just use it without touching the Oauth2 middleware.
Not sure yet why the latter was created and based on which specification, I'll investigate about it.

**Comment by cjford** [comment]
@iMacTia I assume the two middlewares are for the two different versions of OAuth: [1.0](https://tools.ietf.org/html/rfc5849) and [2.0](https://tools.ietf.org/html/rfc6749)

The main relevant difference as I understand it is that OAuth 1 requires you to calculate a cryptographic signature based on a bunch of different parameters for every request. OAuth2 in contrast assumes security [via TLS](https://tools.ietf.org/html/rfc6749#section-10.3), and therefore also allows simply adding a previously obtained access token as-is to any request.

My particular use case is targeting a service which expects a single access token and not a signed request, so as far as I can tell the pain OAuth 1 middleware would not work properly. But if I get a chance I'll play around with it and see if I can verify that.

**Comment by cjford** [comment]
Incidentally, in light of the revelation that OAuth2 relies fully on TLS for security, *technically* this is not a bug (although it may be [a terrible idea](https://hueniverse.com/2010/09/29/oauth-bearer-tokens-are-a-terrible-idea/)). That said I still believe a header over query string is a safer option, and ideally the default.

**Comment by iMacTia** [comment]
@cjford I see, then if the request signature is an issue for your service, I would still ask you to implement the configurable new behaviour, but please make the default one behaving exactly as the current implementation (which as far as I understood adds the token to both parameter and header)

**Comment by syguer** [comment]
Thx for reply and fix!
