### ISSUE TITLE
Timing middleware pull request

### ISSUE THREAD

**Issue by aserafin** [lostisland/faraday_middleware#133]
Hi, 

I've put together very simple [timing middleware](https://github.com/aserafin/faraday_timing_middleware) for Faraday. If you think it will be good to have it here I'm happy to port it and open pull request :)

**Comment by iMacTia** [comment]
@aserafin thanks for contributing to Faraday by creating this middleware 😃!

Unfortunately we can't accomodate all middlewares into faraday_middleware as that would mean we need to also actively maintain all of them 😅.

I'm really grateful for your contribution, but it'd be better to keep it under your control to ensure it is kept up-to-date and maintained properly.
