### ISSUE TITLE
Parsing Image and PDF response 

### ISSUE THREAD

**Issue by arpanchaudhury** [lostisland/faraday_middleware#135]
I have encountered a scenario where I need to call an external API to get images and pdfs and parse them to corresponding filetypes before sending to the user. I could not found any of such parser in Faraday. Is it a good idea to add it? Or is it better do the keep these separate?

**Comment by iMacTia** [comment]
@arpanchaudhury sorry for being late.
Yes I wouldn't consider this a "core" middleware so feel free to create a separate one and share the link with others here 👍 !
