### ISSUE TITLE
FollowRedirects: URL in location header gets encoded incorrectly

### ISSUE THREAD

**Issue by argos83** [lostisland/faraday_middleware#138]
Hi!
   I'm using `FaradayMiddleware::FollowRedirects`, I'm doing a GET to a URL which results in the server returning 302 response with a Location header that looks like the following:

```
https://host.example.com/some/path#someanchor
```

In [this method](https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/response/follow_redirects.rb#L120) the URL in the location header gets (IMO, incorrectly) encoded to the following:

```
https://host.example.com/some/path%23someanchor
```

Resulting in a 404 response whet the redirection is followed.

(note: browsers don't have this behavior, they don't  encode `#` and the correct URI is requested)

If you agree I can create a PR adding the `#` char to the `URI_UNSAFE` regex so it doesn't get encoded.

(This is on FaradayMiddleware 0.10.0, with mri ruby 2.2.3)

Thanks for this great library.

Seba.

**Comment by argos83** [comment]
Sorry, I've just found this was reported (and atm in open state) in #117. I did a search before reporting this one, but apparently missed that one out.

**Comment by iMacTia** [comment]
Fixing with #150

**Comment by dentarg** [comment]
This could be closed now, right?

**Comment by iMacTia** [comment]
Indeed, thanks!
