### ISSUE TITLE
undefined method `sax_parse' for Ox:Module

### ISSUE THREAD

**Issue by anildias** [lostisland/faraday_middleware#139]
Im getting this error when I call object.get.body

`object = Faraday.new 'url' do |conn|`
          `conn.headers['referer'] = 'referer url'`
          `conn.response :xml`
          `conn.adapter Faraday.default_adapter`
`end`
`object.params = {:id => 123}`

when I call `object.get.body` , throws this exception

error backtrace 

/usr/local/rvm/gems/ruby-2.2.2/gems/multi_xml-0.5.5/lib/multi_xml.rb:138:in `parse'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response/parse_xml.rb:9:in`block in class:ParseXml'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:48:in `call'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:48:in`parse'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:32:in`block in call'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in`call'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in`run_request'
/usr/local/rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'

**Comment by olleolleolle** [comment]
@anildias Hello! I got interested in your issue, and dug a little bit.

**Question**: was Ox code was yet loaded in your codebase? Check for a `require 'ox'` in your code.

Background links for my question: Faraday Middleware [only hands over the XML](https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/response/parse_xml.rb) to the MultiXml gem's `.parse` method - resolving to its ox backend, which in turn calls `Ox.sax_parse` ([source link here](https://github.com/sferik/multi_xml/blob/b195eff9f8f12df850d4f6554910dda6c6a6a4fa/lib/multi_xml/parsers/ox.rb#L30-L34)). And, for completeness: [`Ox.sax_parse explained` in Ox](https://github.com/ohler55/ox/blob/072b72d17fc65465ac879d49f68baa6bd32764de/lib/ox/sax.rb#L3)

**Comment by olleolleolle** [comment]
Here's a working example program: it displays the XML from the sitemap of Dagens Nyheter in Sweden.

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'faraday_middleware'
  gem 'multi_xml'
  gem 'ox'
end

url = 'https://www.dn.se/sitemap.xml'

object = Faraday.new url do |conn|
  conn.headers['referer'] = 'https://hynek.me/articles/python-in-production/'
  conn.response :xml
  conn.adapter Faraday.default_adapter
end
object.params = {:id => 123 }

p object.get.body
```

**Comment by olleolleolle** [comment]
Hope this helps!
