### ISSUE TITLE
Add 308 to REDIRECT_CODES

### ISSUE THREAD

**Issue by sid137** [lostisland/faraday_middleware#147]
Hi,

I'm having several public APIs (such as Cisco Meraki) send responses with 308 redirects, and lost a few hours because the middleware only redirects up to 307.  Could you add 308 to the list of supported redirects?

Thanks

**Comment by iMacTia** [comment]
Hi @sid137 and thanks for your issue.
I think this is a reasonable and useful addition, but I've never used Cisco Meraki or any other API returning this error so I'll need to double-check what's the correct format before preparing a PR on this.
Can't provide an ETA at the moment but happy to review a PR if anyone have more time than me :)
