### ISSUE TITLE
Checksum for 0.11.0 on rubygems.org is invalid

### ISSUE THREAD

**Issue by mfischer-zd** [lostisland/faraday_middleware#152]
```
Bundler cannot continue installing faraday_middleware (0.11.0).
The checksum for the downloaded `faraday_middleware-0.11.0.gem` does not match the checksum given by the server. This means the contents of the downloaded gem is different from what was uploaded to the
server, and could be a potential security issue.

To resolve this issue:
1. delete the downloaded gem located at: `/usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.11.0/faraday_middleware-0.11.0.gem`
2. run `bundle install`

If you wish to continue installing the downloaded gem, and are certain it does not pose a security issue despite the mismatching checksum, do the following:
1. run `bundle config disable.checksum_validation true` to turn off checksum verification
2. run `bundle install`

(More info: The expected SHA256 checksum was "c56bb3661af1d5057e578d72d2f9e93ab52630b74ebe37ce1118c93a6ddff56b", but the checksum for the downloaded gem was
"ff2bdbb6bdd5b2293f8ce7cb93572318dd068506e12f987f04a65209a2bc69cb".)
```

**Comment by lebibin** [comment]
Also encountering this issue, as workaround I explicitly specified version `0.10.1` in `Gemfile`.

**Comment by mike-bailey** [comment]
Also encountered this issue locally and encountered issue on https://travis-ci.org/dblock/slack-google-bot/builds/194117077

**Comment by chulkilee** [comment]
See bundler/bundler#5332

**Comment by iMacTia** [comment]
I'm really sorry for this guys.
I'm releasing 0.11.0.1 now and see if this time Rubygems will generate the correct checksum.
As @lebibin suggested, you can temporarily force v0.10.1.
I would avoid ignoring running `bundle config disable.checksum_validation true` as that will lower your security

**Comment by iMacTia** [comment]
Version 0.11.0.1 released and I was able to install it on my computer through `bundle update`.
@mfischer-zd @lebibin @mike-bailey can you please confirm to me that it's now working for you as well?

**Comment by sondremare** [comment]
I can confirm that my CircleCi build started working again after you release 0.11.0.1. Thanks

**Comment by lebibin** [comment]
all working for me now as well, thanks @iMacTia for the update!

**Comment by iMacTia** [comment]
Great, I'm going to close then as it seems solved.

**Comment by kboygit** [comment]
Thank you this worked for me as well ...
