### ISSUE TITLE
Gzip and JSON middleware failing combined

### ISSUE THREAD

**Issue by borsothy** [lostisland/faraday_middleware#153]
Even though I did not find any documentation about it, I believe the order middlewares run is the following:
1. request middleware
2. middleware
request out, response back, then...
3. response middleware
4. middleware

Now, since JSON is implemented in two separate request/response middlewares, but gzip is a "general" one, the order they run is:
1. JSON encode
2. compress
3. JSON  parse
4. decompress

Obviously JSON encoding will fail, because it will try to parse the compressed message body. Please confirm if this is indeed an issue, or I'm doing something wrong.

**Comment by iMacTia** [comment]
Hi @borsothy, middlewares don't have a predefined order, they're executed in the same order that you add them to the stack.
Allow me to point out a couple of useful points in this case:

1. The GZIP middleware doesn't perform any compression on the request AFAIK. It should just set the correct headers to tell the server he can handle GZIP.
2. The JSON middleware is in reality 2 separate middlewares, one for encoding the request and one for decoding the response (I'll refer to them as JSON REQUEST and JSON RESPONSE)

So if you define your Faraday connection as:

```ruby
conn = Faraday.new(...) do |f|
  f.request :json
  f.response :json, :content_type => /\bjson$/
  f.use FaradayMiddleware::Gzip
end
```

This should make the order of middlewares as:

1. JSON REQUEST encodes request
2. JSON RESPONSE (does nothing)
3. GZIP adds headers
4. Adapter perform the request and get the response
5. GZIP decompress
6. JSON RESPONSE decode request
2. JSON REQUEST (does nothing)


I suppose this is what you want and I'd expect this to work.
As you can see, middlewares are called in a "nested" order so if you move the gzip up or down (e.g. between the 2 JSON middlewares) that will cause the JSON to fail

**Comment by borsothy** [comment]
My bad, it really does work this way. Thanks! :)

**Comment by iMacTia** [comment]
Glad I could help 👍 
No worries, it really is hard to get used to it but once you understand how it works you can easily master it 😃
