### ISSUE TITLE
FollowRedirects: `safe_escape': undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by dentarg** [lostisland/faraday_middleware#158]
If the server doesn't send the `Location` header on a redirect response (e.g. 301), the FollowRedirects middleware blows up:

```
$ ruby -v ; ruby -rfaraday_middleware -e 'Faraday.new("http://mockbin.org/bin/efd53146-609b-4bc5-89f8-530a55176203") { |faraday| faraday.use FaradayMiddleware::FollowRedirects ; faraday.adapter Faraday.default_adapter }.get'
ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
/Users/dentarg/.gem/ruby/2.2.6/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:128:in `safe_escape': undefined method `split' for nil:NilClass (NoMethodError)
	from /Users/dentarg/.gem/ruby/2.2.6/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:92:in `update_env'
	from /Users/dentarg/.gem/ruby/2.2.6/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:83:in `block in perform_with_redirection'
	from /Users/dentarg/.gem/ruby/2.2.6/gems/faraday-0.12.1/lib/faraday/response.rb:61:in `on_complete'
	from /Users/dentarg/.gem/ruby/2.2.6/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:80:in `perform_with_redirection'
	from /Users/dentarg/.gem/ruby/2.2.6/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
	from /Users/dentarg/.gem/ruby/2.2.6/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/dentarg/.gem/ruby/2.2.6/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /Users/dentarg/.gem/ruby/2.2.6/gems/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
	from -e:1:in `<main>'
```

```
$ curl -s -v http://mockbin.org/bin/efd53146-609b-4bc5-89f8-530a55176203
*   Trying 104.28.22.173...
* Connected to mockbin.org (104.28.22.173) port 80 (#0)
> GET /bin/efd53146-609b-4bc5-89f8-530a55176203 HTTP/1.1
> Host: mockbin.org
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 OK
< Date: Sat, 24 Jun 2017 10:54:00 GMT
< Content-Length: 0
< Connection: keep-alive
< Set-Cookie: __cfduid=d4c7ad4f8a6d09d4b7e9985a7d63df4e91498301639; expires=Sun, 24-Jun-18 10:53:59 GMT; path=/; domain=.mockbin.org; HttpOnly
< Etag: W/"0-1B2M2Y8AsgTpgAmY7PhCfg"
< Via: 1.1 vegur
< Server: cloudflare-nginx
< CF-RAY: 373f25814238724d-AMS
<
* Connection #0 to host mockbin.org left intact
```

**Comment by iMacTia** [comment]
Hi @dentarg and thanks for pointing this out!

I'm really we introduced this issue with one of the recent commits.
However, I double-checked the RFC for HTTP 1.1 and that states that the Location header SHOULD be provided by the server.
I can't think of a situation where the Location header could be missing hence I don't understand how this can actually be an issue.
Would you please explain in which circumstances your server application is return a 30x response with missing Location header?

**Comment by dentarg** [comment]
> However, I double-checked the RFC for HTTP 1.1 and that states that the Location header SHOULD be provided by the server.
> I can't think of a situation where the Location header could be missing hence I don't understand how this can actually be an issue.
> Would you please explain in which circumstances your server application is return a 30x response with missing Location header?
> 
I agree that there's probably isn't exist a legitimate reason to not respond with the location header on a 30x response, but the fact is that the internet is full of misconfigured servers. (Yes, I've seen them.) I think it makes sense to take that into account when building general purpose HTTP libraries and tools. Thanks for the merge!

**Comment by iMacTia** [comment]
I understand. I still don't agree with the idea but this might make Faraday more stable and is not making it heavier, so I'll have a look at the PR

**Comment by dentarg** [comment]
Thanks
