### ISSUE TITLE
faraday_middleware 0.12.0 incompatible with oj_mimic_json

### ISSUE THREAD

**Issue by dahlb** [lostisland/faraday_middleware#164]
seems the oj_mimic_json which monkey patches oj as a replacement for JSON.parse does not allow nil to be passed into parse, needs empty hash or no parameter so default value of parameter will be used

gem 'oj_mimic_json'

Faraday::ParsingError:
       options must be a hash.
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday_middleware-0.12.0/lib/faraday_middleware/response/parse_json.rb:11:in `parse'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday_middleware-0.12.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday_middleware-0.12.0/lib/faraday_middleware/response_middleware.rb:54:in `parse'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday_middleware-0.12.0/lib/faraday_middleware/response_middleware.rb:40:in `process_response'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday_middleware-0.12.0/lib/faraday_middleware/response_middleware.rb:33:in `block in call'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.2/lib/faraday/response.rb:61:in `on_complete'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday_middleware-0.12.0/lib/faraday_middleware/response_middleware.rb:31:in `call'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.2/lib/faraday/response.rb:8:in `call'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.2/lib/faraday/request/url_encoded.rb:15:in `call'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday_middleware-0.12.0/lib/faraday_middleware/request/encode_json.rb:24:in `call'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
     # /Users/brendandahl/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.2/lib/faraday/connection.rb:186:in `post'

**Comment by iMacTia** [comment]
Hi @dahlb, good news!
This has already been addressed in #163.
I'll release it today or tomorrow as an hotfix
