### ISSUE TITLE
Follow meta refresh tag

### ISSUE THREAD

**Issue by v3rmin** [lostisland/faraday_middleware#172]
Hi, in Mechanize there is a setting named `follow_meta_refresh` to follow the redirects specified by the `<meta http-equiv="refresh" content="0; url=http://example.com/">` tag. Do you know any middleware for Faraday to handle that type of redirections?

**Comment by dalthon** [comment]
Just did that and opened a pull request (https://github.com/lostisland/faraday_middleware/pull/179)

**Comment by iMacTia** [comment]
#179 was closed so as of today there's still no official middleware in `faraday_middleware` to do that.
However someone might have created a gem with such a middleware, and we're simply unaware of it.

I'll be closing this as a non-issue, but if you find such a gem please share it with the community as it might be interesting for future readers.
