### ISSUE TITLE
Deprecation warning re Faraday::Error::ClientError

### ISSUE THREAD

**Issue by niborg** [lostisland/faraday_middleware#197]
Using Faraday 0.16.2 and the FollowRedirects middleware, a `DEPRECATION WARNING: Faraday::Error::ClientError is deprecated! Use Faraday::ClientError instead.` comes up. See [this line](https://github.com/lostisland/faraday_middleware/blob/be685418ba8ef4c428f726e7b943b2fb64860ec5/lib/faraday_middleware/response/follow_redirects.rb#L6).

**Comment by lindsim** [comment]
this is fixed here: https://github.com/lostisland/faraday_middleware/pull/196/files

**Comment by jcoyne** [comment]
Any chance we'll see this in a release soon?

**Comment by rainerborene** [comment]
+1

**Comment by twistapp** [comment]
+1

**Comment by iMacTia** [comment]
Those warnings have been disabled by default in Faraday v0.17.3, you can re-enable them later when you'll be planning an upgrade to v1.0 with an ENV variable
