### ISSUE TITLE
Add support for Faraday 1.0

### ISSUE THREAD

**Issue by jcoyne** [lostisland/faraday_middleware#199]
```
      faraday_middleware (~> 0.13) was resolved to 0.13.1, which depends on
        faraday (>= 0.7.4, < 1.0)
```

**Comment by shlima** [comment]
+1

**Comment by iMacTia** [comment]
#196 have now been merged so master branch is now compatible with Faraday 1.0 🎉 
We're going to do some extra changes before releasing it officially, but if you're in a rush you can use master for the time being
