### ISSUE TITLE
Ship v1.0

### ISSUE THREAD

**Issue by iMacTia** [lostisland/faraday_middleware#200]
After merging #196, `master` branch should be compatible with Faraday 1.0, however before shipping a 1.0 release we might want to do also the following:

* [x] Add Ruby 2.7 to the CI and check for warnings
* [x]  Enable RuboCop and code-style the whole project #204
* [x]  Move from Travis to GitHub Actions #202
* [x] Thank all contributors in 1.0 release note

**Comment by johnlcox** [comment]
Is there an ETA on when this might be released? Is there anything I can do to help out?

**Comment by olleolleolle** [comment]
Hi John, thanks for asking - there were some API key issues re: RubyGems publishing to fully overcome, and that's being given thought.

The other detail  would be to fully lint the darned thing.

In Faraday, we took the route of "make 1 separate Cop rule per PR" in fully linting the codebase. https://github.com/lostisland/faraday_middleware/pull/203 is one such PR in this repository.

We could need a RuboCop linting Issue like that, to manage the list of things already done.

**Comment by olleolleolle** [comment]
I have now marked both "enable RuboCop in CI", "lint the whole codebase" and "Move to GitHub Actions" as done.

**Comment by olleolleolle** [comment]
Perhaps one additional step: check the codebase for 2.3-ness. There were somewhat old 1.8, 1.9 compatibility fixes in here, and with the recent 2.3+ decision, we have an opportunity to remove them.

**Comment by cice** [comment]
> Perhaps one additional step: check the codebase for 2.3-ness. There were somewhat old 1.8, 1.9 compatibility fixes in here, and with the recent 2.3+ decision, we have an opportunity to remove them.

👍 for removing tec debt, but would be nice to be able to use faraday 1.0 :) maybe this can be postponed to v1.0.1?

**Comment by olleolleolle** [comment]
As a status report, there's now a 1.0.0.rc1 to try out.

**Comment by iMacTia** [comment]
Everyone's feedback would be extremely appreciated if you had any low-risk project you could try this out in combination with Faraday 0.x and 1.0.

Thank you!

**Comment by iMacTia** [comment]
This is now done 🎉!
Thanks to @BobbyMcWho, @onk and @d-m-u for the help on getting this over the line ❤️
