### ISSUE TITLE
RuboCop Quest Issue

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday_middleware#204]
## Basic Info

We are linting the whole codebase using RuboCop. ✨ 

This is a list of all the rules in the `.rubocop_todo.yml` when we started. The checkmarks mean "this is fixed and merged to master".

If you create a PR to fix one of these, use the `--only` option in RuboCop, to focus the effort on 1 kind of fix. It's so easy to get overwhelmed when reviewing code like this. (If you fix slightly more than that, no biggie. This is all about keeping the changes reviewable.)

<details>

```bash
# edit .rubocop.yml, commenting out the first line -
#   this removes the "ignore the TODOs" setting

# Auto-correct with only 1 rule
rubocop -a --only Name/OfTheRuleYouAreFixing --auto-correct

# Re-generate the config file
rubocop --auto-gen-config

# Revert line 3 in .rubocop_todo.yml
# This will avoid PR conflicts

# Inspect to see if it looks OK
git diff

# Re-set the TODO list
git checkout .rubocop.yml

# Add and commit the change
git add .
git commit -m"chore: RuboCop lint Name/OfTheRuleYouAreFixing"
```
<summary>A workflow</summary>

</details>

## Issue description

- [x] Bundler/OrderedGems #205  
- [x] Layout/ArgumentAlignment #206 
- [x] Layout/ArrayAlignment #207
- [x] Layout/BlockEndNewline #208
- [x] Layout/ElseAlignment
- [x] Layout/EmptyLineAfterGuardClause
- [x] Layout/EmptyLineAfterMagicComment
- [x] Layout/EmptyLineBetweenDefs
- [x] Layout/EmptyLinesAroundBlockBody
- [x] Layout/EmptyLinesAroundClassBody
- [x] Layout/EndAlignment
- [x] Layout/FirstArgumentIndentation
- [x] Layout/HashAlignment
- [x] Layout/IndentationConsistency
- [x] Layout/IndentationWidth
- [x] Layout/MultilineBlockLayout
- [x] Layout/MultilineHashBraceLayout
- [x] Layout/MultilineMethodCallBraceLayout
- [x] Layout/MultilineMethodCallIndentation
- [x] Layout/SpaceAfterComma
- [x] Layout/SpaceAroundOperators
- [x] Layout/SpaceBeforeBlockBraces
- [x] Layout/SpaceInsideArrayLiteralBrackets
- [x] Layout/SpaceInsideBlockBraces
- [x] Layout/SpaceInsideHashLiteralBraces
- [x] Layout/SpaceInsidePercentLiteralDelimiters
- [x] Lint/AssignmentInCondition #228 
- [x] Lint/Loop
- [x] Lint/SendWithMixinArgument
- [x] Lint/UnusedBlockArgument
- [x] Lint/UnusedMethodArgument
- [ ] Metrics/AbcSize
- [x] Metrics/BlockLength
- [ ] Metrics/MethodLength
- [x] Naming/ConstantName #225 
- [x] Naming/PredicateName
- [x] Naming/RescuedExceptionsVariableName
- [x] Naming/VariableNumber
- [x] Security/MarshalLoad
- [x] Style/AccessModifierDeclarations
- [x] Style/AndOr
- [x] Style/BlockDelimiters
- [x] Style/BracesAroundHashParameters
- [x] Style/CaseEquality
- [x] Style/Documentation
- [x] Style/DoubleNegation
- [x] Style/EmptyLiteral
- [x] Style/Encoding
- [x] Style/ExpandPathArguments
- [x] Style/FormatString #233
- [x] Style/FormatStringToken #233
- [x] Style/FrozenStringLiteralComment
- [x] Style/GuardClause
- [x] Style/HashSyntax
- [x] Style/IfUnlessModifier
- [x] Style/Lambda
- [x] Style/MethodCallWithoutArgsParentheses
- [x] Style/MultilineTernaryOperator #230 
- [x] Style/MutableConstant
- [x] Style/NumericPredicate
- [x] Style/ParallelAssignment
- [x] Style/PercentLiteralDelimiters
- [x] Style/RedundantPercentQ
- [x] Style/RedundantSelf
- [x] Style/RegexpLiteral
- [x] Style/SafeNavigation
- [x] Style/SignalException
- [x] Style/SingleLineMethods
- [x] Style/StringLiterals #203 
- [x] Style/StructInheritance #229 
- [x] Style/SymbolArray
- [x] Style/SymbolProc
- [x] Style/TrailingCommaInHashLiteral
- [x] Style/WordArray
- [x] Style/YodaCondition
- [x] Layout/LineLength

(Here - we will add each of the RuboCop Cops in order.)

See #200

**Comment by iMacTia** [comment]
@d-m-u @onk thanks for your patience, I've resolved a bunch of offences automatically and update the list above 👍
If you want to help, please follow the below:
1. Leave a comment here before starting stating the rule(s) you're taking care of
2. Branch from `master` into a new branch
3. Remove the rule(s) you want to fix from the `.rubocop_todo.yml` file
4. Run `rubocop` to see the offenses
5. Fix the offences
6. Commit, push and open a PR

Thanks ❤️ !

**Comment by d-m-u** [comment]
I've got the Lint/Loop one.

**Comment by d-m-u** [comment]
I've also got the Style/GuardClause.

**Comment by olleolleolle** [comment]
Thank you, everyone! I am declaring a victory: there are now AbcSize + MethodLength left, and those are just set in the TODO file to a current "max" value which we can prune downwards as we go.

This was a significant piece of formatting - thanks so much for stepping up and helping out with this. A special round of applause for @onk and @d-m-u who picked up the bulk of the pieces left after @iMacTia did the initial automated push.

Closing this Issue feels very good. Thanks!

🌻 /Olle
