### ISSUE TITLE
ruby 2.7.0 warnings

### ISSUE THREAD

**Issue by vchepkov** [lostisland/faraday_middleware#245]
After upgrade to ruby 2.7.0 warnings are bing emitted:
```
/usr/local/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```

**Comment by olleolleolle** [comment]
These warnings, can you find them in current master branch?

**Comment by vchepkov** [comment]
Sorry, I have checked the latest gem version and the code causing warning by the interpreter was still there.
