### ISSUE TITLE
New version is causing some errors in my tests

### ISSUE THREAD

**Issue by feihokpai** [lostisland/faraday_middleware#294]
All tests that execute the line below has errors, after upgrading to version 1.2.1:

```ruby
raise EML::Error, response.body.dig('message') unless response.success?
```

One of the tests with error:

```ruby
fit 'raises an exception if the API fails' do
  expect do
    webmock :post, { /test/ => 'eml/error.500.json' }
    subject.post 'test'
  end.to raise_error(EML::Error, 'Test error')
end
```

The value returned by response.body is the string below, present in the test file `spec/support/stubs/eml/error.500.json`

```json
{
  "code": 500,
  "message": "Test error"
}
```

The error message is:
```
expected EML::Error with "Test error", got #<NoMethodError: undefined method `dig' for "{\n  \"code\": 500,\n  \"message\": \"Test error\"\n}\n"..., response.body.dig('message') unless response.success?
```

In the version 1.2.0, the value returned by response.body was a Hash, in the 1.2.1, it returns as a string.

**Comment by iMacTia** [comment]
Hi @feihokpai this might be related to #293.
Could you please:
1. Share more details about how you setup the Faraday connection; and 
2. Share the mock server implementation and check that the correct JSON `Content-Type` header is returned?

**Comment by feihokpai** [comment]
To turn around the problem, I created a module with a method stubbing the requests, adding the headers.

module WebmockSupport
  def webmock_stub_request(file_url:, status: 500, request_type: :post, url_request: /test/)
    stub_request(request_type, url_request).to_return(
      status: status,
      body: File.read("spec/support/stubs/#{file_url}"),
      headers: { 'Content-Type' => 'application/json' }
    )
  end
end
