### ISSUE TITLE
Breaking change?

### ISSUE THREAD

**Issue by nroose** [lostisland/faraday_middleware#295]
Not sure of the details (yet?), but it does seem like updating to 1.2.1 from 1.2.0 did cause a response to change from being a ruby object to being a json string. I don't have a small code set that reproduces this, but thought I would put this here. We will be using 1.2.0 for now.

**Comment by iMacTia** [comment]
Hi @nroose, this is likely caused by [this](https://github.com/lostisland/faraday_middleware/issues/293).
Can you check if the response you get from the server has the correct `Content-Type` header?

**Comment by nroose** [comment]
Thanks!
