### ISSUE TITLE
FollowRedirects doesn't actually follow redirects...

### ISSUE THREAD

**Issue by hypomodern** [lostisland/faraday_middleware#32]
...or I am unable to comprehend how to make it work :). It's been one of those weekends, so I might be Doin' It Wrong (TM), but I don't think so.

So, here's a transcript from a test against http://httpstat.us/302. You can see in the basic `Faraday.get` example that the response is an ordinary HTTP 302 with a location header. All good.

```
1.9.3p125 :005 > Faraday.get("http://httpstat.us/302")
 => #<Faraday::Response:0x000001013bf860 @env={:method=>:get, :body=>"302 Found\r\n\r\nLocation: http://httpstat.us", :url=>#<Addressable::URI:0x809d77d8 URI:http://httpstat.us/302>, :request_headers=>{}, :parallel_manager=>nil, :request=>{:proxy=>nil}, :ssl=>{}, :status=>302, :response_headers=>{"server"=>"nginx", "date"=>"Sun, 01 Apr 2012 22:20:36 GMT", "content-type"=>"text/plain", "connection"=>"close", "location"=>"http://httpstat.us", "access-control-allow-origin"=>"*", "content-length"=>"41", "x-varnish"=>"1462090777", "age"=>"0", "via"=>"1.1 varnish"}, :response=>#<Faraday::Response:0x000001013bf860 ...>}, @on_complete_callbacks=[]> 
```

However, if I construct a Faraday connection with the `FaradayMiddleware::FollowRedirects` middleware mounted, the response is not what I would expect:

```
1.9.3p125 :003 > conn = Faraday.new("http://httpstat.us/302") { |b| b.use FaradayMiddleware::FollowRedirects }
 => #<Faraday::Connection:0x00000100cd0270 @headers={}, @params={}, @options={}, @ssl={}, @parallel_manager=nil, @scheme="http", @port=nil, @host="httpstat.us", @path_prefix="/302", @proxy=nil, @builder=#<Faraday::Builder:0x00000100ccfb90 @handlers=[FaradayMiddleware::FollowRedirects]>> 
1.9.3p125 :004 > conn.get("/")
 => #<Faraday::Response:0x00000100cdb350 @env={:method=>:get, :body=>nil, :url=>#<Addressable::URI:0x8066dc14 URI:http://httpstat.us/>, :request_headers=>{}, :parallel_manager=>nil, :request=>{:proxy=>nil}, :ssl=>{}, :response=>#<Faraday::Response:0x00000100cdb350 ...>}, @on_complete_callbacks=[]> 
```

Note both body and status are `nil`. My read is that somehow the request isn't finished, but some exploration of the middleware's source code didn't reveal a whole lot to me. My apologies for the bug report without a pull request, but I'm still new to Faraday :). Let me know if I can provide any additional information.

Thanks!

**Comment by Jamedjo** [comment]
I had a variation on this where it only worked if I specified the adapter after `c.use FaradayMiddleware::FollowRedirects, limit: 3` and not if specified before

**Comment by freeslugs** [comment]
@mislav you're so sassy...
