### ISSUE TITLE
OAuth2 causes Rack::Cache misses

### ISSUE THREAD

**Issue by justinfrench** [lostisland/faraday_middleware#61]
I'm not sure if this is an with the order of my middleware, or something I don't understand about OAuth2, but as soon as I add OAuth2 to the stack, all subsequent requests are misses. Removing OAuth2 means subsequent requests are "fresh".

Here's a cut-down stack that seems to work from a cache perspective:

```
        c.use Faraday::Response::Logger
        c.use FaradayMiddleware::RackCompatible, Rack::Cache::Context,
         :metastore   => "memcached://localhost:11211/meta",
         :entitystore => "memcached://localhost:11211/body",
         :ignore_headers => %w[Set-Cookie X-Content-Digest]
        c.use Faraday::Adapter::NetHttp
```

And here's one that seems to fail (I see a new HTTP request to the API) once I add-in OAuth2:

```
        c.use FaradayMiddleware::OAuth2, @token
        c.use Faraday::Response::Logger
        c.use FaradayMiddleware::RackCompatible, Rack::Cache::Context,
         :metastore   => "memcached://localhost:11211/meta",
         :entitystore => "memcached://localhost:11211/body",
         :ignore_headers => %w[Set-Cookie X-Content-Digest]
        c.use Faraday::Adapter::NetHttp
```

Where's the right place in the stack for OAuth2? What am I missing?

**Comment by olleolleolle** [comment]
(Closing this, it's been a while since last interaction from the original poster. Thanks all for the help!)
