### ISSUE TITLE
Rash / Hashie Name Issues

### ISSUE THREAD

**Issue by tcocca** [lostisland/faraday_middleware#91]
So I believe that Faraday Middleware is using my gem Rash: https://github.com/tcocca/rash for the Rashify middleware however, somebody filed a ticket with my gem: https://github.com/tcocca/rash/issues/9  as it appears that Hashie has added their own Rash type: https://github.com/intridea/hashie/blob/master/lib/hashie/rash.rb  which is clearly not intended to provide the same functionality (https://github.com/intridea/hashie#rash)

Looks like Hashie::Rash first appeared in Hashie v2.1.0

I'm not sure what the best solution is here.  I could re-name my gem and extension but there are a lot of gems using it and I believe you are the biggest of those gems in terms of usage so I wanted to get your thoughts on the situation.

I am thinking I ned to release a new minor version for my Rash gem that locks down the hashie dependency to < 2.1.0.  Then I will either need to release a new major version of Rash that changes the class name and has a Hashie dependency that is either > 2.1.0 or really no set version.  OR I just release a new gem with a new name altogether.  I think this is a the best option as it will be the least confusing to people looking to use the gem.

Unfortunately, like a lot of other gems it seems that faraday_middleware is "soft loading" rash and not requiring it in the gemspec.  I think this could potentially be a large problem.

Just wanted to get your thoughts/opinions.  Also, any ideas for a new name for my version of Rash?

**Comment by elyobo** [comment]
hashie's rash is completely different to tcocca's rash.

Unfortunately it doesn't seem that there has been any action on this; faraday_middleware still uses tcocca's rash, which conflicts with recent versions of hashie's rash.  No new version of tcocca's rash has been released to resolve this either, which leaves it unusuable if you're using a recent hashie version.

**Comment by dblock** [comment]
I looked at the code, specifically the differences are:

* method access (eg. `.name` for ['name']) doesn't exist in Hashie's Rash
* camelCase translation (eg. `myName` becomes 'my_name') doesn't exist in Hashie's Rash

Made https://github.com/lostisland/faraday_middleware/pull/128 that replaces tcocca/rash by Hashie::Rash, with the behavior changes. That's one option, I am not sold that that's the right thing to do. Maybe the right thing to do would be to remove `Rashify` alltogether from faraday_middleware?

I think the other option is to remove Rashify alltogether and to introduce a way to compose desired Hashie behavior using extensions. I opened https://github.com/lostisland/faraday_middleware/issues/129, comments welcome.

**Comment by dblock** [comment]
Btw, the tests here use tcocca/rash, but FaradayMiddleware will use whatever class you have. There's no gem dependency. You'll just get different behavior than the test in your application.

**Comment by elyobo** [comment]
Given that the camel case translation is the entire point of tcocca's Rash you have confirmed that they're totally different.  Replacing one with the other would be a large and confusing functional change for the middleware.

**Comment by dblock** [comment]
Right, you should close #129 and we should replace it with a Hashie version of camelCase translation.

**Comment by elyobo** [comment]
I think #129 is a different idea and (as I've just commented there) easily doable with the existing Mashify middleware.

Really, I think tcocca's Rash should use a different module name so that it doesn't conflict, release a major version update, and then the Rashify middleware should be updated to use that version with the new name.  Seems straightforward and everything works fine.

**Comment by iMacTia** [comment]
This should now be fixed as of #136
